### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by JesOb** [mob-sakai/CSharpCompilerSettingsForUnity#1]
Plugin do something and adds Compilation directives CSHARP_8_OR_LATER...
but actually can not compile any C# 8 code
even csc.rsp -langversion:8.0 stop compiler function with error of uncompatible lang version

**Screenshots**
![изображение](https://user-images.githubusercontent.com/3026249/93425335-6defd700-f8c2-11ea-8c0f-11ee15c84c90.png)

**Environment (please complete the following information):**
 - Unity Version 1.0.0
 - Platform: Editor(Windows)
 - Unity version: 2019.4.9f1
 - Build options: IL2CPP, .Net 4.x, URP

**Comment by JesOb** [comment]
Test with new empty project shows the same
![изображение](https://user-images.githubusercontent.com/3026249/93426465-c45e1500-f8c4-11ea-8348-536ae8ea1c92.png)

csc.rsp
-langversion:8.0

**Comment by mob-sakai** [comment]
@Jes28 
I want to ask you a few questions.

* Do you see a log for `CscSettings`?
![image](https://user-images.githubusercontent.com/12690315/93427846-77486600-f8f9-11ea-8adf-0cad4f489706.png)
* Does `Library/Microsoft.Net.Compilers.3.5.0/tools/csc.exe` exist?
* Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
OK, the issue reproduced on my environment (Windows).
On macOS, it works.

**Comment by mob-sakai** [comment]
@Jes28 
Please try to use `v1.0.1`

**Comment by JesOb** [comment]
Work like a charm :)
