### ISSUE TITLE
How to access privates & internals of Unity?

### ISSUE THREAD

**Issue by laicasaane** [mob-sakai/CSharpCompilerSettingsForUnity#13]
The note on OpenSesameCompilerForUnity said it had been integrated into this project, but I can't find any setting to allow accessing privates & internals.

**Comment by VolodymyrBS** [comment]
You need to set the `OpenSesame.Net.Compilers` or `OpenSesame.Net.Compilers.Toolset` package as a custom compiler package name.
Look at [usage page](https://github.com/mob-sakai/CSharpCompilerSettingsForUnity#usage) to configure it.

**Comment by laicasaane** [comment]
Oh, my bad, I didn't read it carefully. Thank you!

**Comment by friuns2** [comment]
i still can't access internal types, i tried both OpenSesame.Net.Compilers.Toolset
![image](https://user-images.githubusercontent.com/16543239/132578653-682fd8ef-8ed1-48b2-a02e-a2ac44d85089.png)
