### ISSUE TITLE
Generated local package csproj does not get updated

### ISSUE THREAD

**Issue by KuraiAndras** [mob-sakai/CSharpCompilerSettingsForUnity#4]
**Describe the bug**
When adding a UPM package locally, and then generating a csproj for it through unity, de generated project for the upm package does not get updated when generating.

**To Reproduce**
1. Clone https://github.com/KuraiAndras/CCFUBugSample
2. Open Unity
3. In Preferences -> External Tools -> External Script Editor select Visual Studio 2019
4. In the same settings enable Local packages generation
5. Regenerate project files
6. Open the project in Visual Studio

Unity does not report any compile errors(correctly), while Visual Studio shows an error in CCFUBugSample.SampleService.TestSwitch. This is because in the unity generated CCFUBugSample.csproj the LangVersion property is set to 7.3 instead of 8.

**Expected behavior**
Any generated csproj gets the desired LangVersion property value

**Environment (please complete the following information):**
 - Version 1.1.0
 - Platform: Editor Windows
 - Unity version: 2020.1.8

**Additional context**
If this would cause problems for some users, maybe consider making this behavior optional through settings

**Comment by mob-sakai** [comment]
@KuraiAndras 
Thank you for the reporting!

**Comment by mob-sakai** [comment]
@KuraiAndras 
Fixed in `1.1.1-preview.3`.
Please try it!

**Comment by KuraiAndras** [comment]
Yupp this works now! Thank you
