### ISSUE TITLE
Add option for generating nullable property in csproj

### ISSUE THREAD

**Issue by KuraiAndras** [mob-sakai/CSharpCompilerSettingsForUnity#5]
**Is your feature request related to a problem? Please describe.**
If you want to use nullable reference types after C#8.0 you either have to manually add the
```
<Nullable>enable</Nullable>
```
property to enable nrt or you have to annotate each file with
```
#nullable enable
```

**Describe the solution you'd like**
In the settings there should be an option for adding the Nullable property when adding the desired LangVersion property. One problem might be is when you want only some projects to have the Nullable property but that would require porject-by-project settings which are as of yet not supported anyway.

**Comment by mob-sakai** [comment]
@KuraiAndras 
:+1:

**Comment by KuraiAndras** [comment]
You are doing an amazing work! Next time I will try to open a pull request as well ;)

**Comment by mob-sakai** [comment]
@KuraiAndras 
Sorry.
There seems to be something wrong with the release workflow...
`1.2.0` does not work correctly.

**Comment by mob-sakai** [comment]
`1.2.0` has been released correctly.

**Comment by VolodymyrBS** [comment]
It would be useful if it will be not just bool property but dropdown with all possible values (enable, disable, warnings, annotations).
Sometimes it useful to set Nullable warnings on the project level for large projects.

**Comment by mob-sakai** [comment]
@VolodymyrBS 
I've created an issue as a new feature request. #8 
It will be released soon. :)

**Comment by mob-sakai** [comment]
All nullable parameters were supported! (1.3.0)
